version: '3.3'
services:
  api:
    image: api-angular-course
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
    - ./:/usr/src/app

  web-cli:
    image: api-angular-course
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge